[package]
name = "bog_render"
version = "0.1.0"
edition = "2024"

[dependencies]
bog_collections.workspace = true
bog_color.workspace = true
bog_math.workspace = true

bytemuck = { version = "1", features = ["derive"] }
glyphon = "0.9"
guillotiere = "0.6"
rustc-hash = "2"
wgpu = "25"
