[package]
name = "bog-view"
version = "0.1.0"
edition = "2024"

[dependencies]
bog-core.workspace = true
taffy = { version = "0.8", default-features = false, features = [
    "block_layout",
    "flexbox",
    "grid",
    "calc",
    "content_size",
] }
