[package]
name = "bog_layout"
version = "0.1.0"
edition = "2024"

[dependencies]
bog_math.workspace = true
# Required for #![no_std].
taffy = { version = "0.7", default-features = false, features = [
    "taffy_tree",
    "block_layout",
    "flexbox",
    "grid",
    "content_size",
] }
